# Generated by Django 6.0.6 on 2026-06-30 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_homework_id'),
        ('courses', '0006_alter_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='homework_id',
        ),
        migrations.AddField(
            model_name='message',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_messages', to='courses.homework'),
        ),
    ]
