# Generated by Django 6.0.6 on 2026-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_homework_id_message_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='chat_files/'),
        ),
    ]
