# Generated by Django 6.0.6 on 2026-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='materials/'),
        ),
    ]
