# Generated by Django 6.0.6 on 2026-06-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_homeworkfile_delete_homeworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='file',
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'перевіряється'), ('checked', 'перевірено'), ('need_revision', 'потребує виправлень')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submission_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.homeworksubmission')),
            ],
        ),
    ]
