# Generated by Django 6.0.6 on 2026-07-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.subject'),
        ),
    ]
