# Generated by Django 6.0.6 on 2026-07-12 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_group_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
