# Generated by Django 6.0.6 on 2026-07-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_homeworksubmission_grade'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='schedule.lesson'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
