# Generated by Django 6.0.6 on 2026-07-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_homework_lesson_homework_lesson_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['id']},
        ),
    ]
