# Generated by Django 6.0.6 on 2026-07-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_level_group_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
