# Generated by Django 6.0.6 on 2026-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='homework_files/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='submission_files/'),
        ),
    ]
