# Generated by Django 6.0.6 on 2026-07-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_homeworkfile_file_alter_submissionfile_file'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('lesson', 'lesson_date')},
        ),
    ]
