# Generated by Django 6.0.6 on 2026-07-12 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_alter_homeworksubmission_grade'),
        ('users', '0002_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.group')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_date', models.DateField()),
                ('makeup_date', models.DateField(blank=True, null=True)),
                ('makeup_start_time', models.TimeField(blank=True, null=True)),
                ('makeup_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='schedule.lesson')),
                ('makeup_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_absences', to='schedule.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_lessons', to='users.student')),
            ],
            options={
                'unique_together': {('student', 'lesson', 'missed_date')},
            },
        ),
        migrations.CreateModel(
            name='LessonParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='schedule.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_participations', to='users.student')),
            ],
            options={
                'unique_together': {('lesson', 'lesson_date', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('exception_type', models.CharField(choices=[('cancelled', 'Скасовано'), ('rescheduled', 'Перенесено')], max_length=20)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='schedule.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'original_date')},
            },
        ),
    ]
