# Generated by Django 6.0.6 on 2026-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonparticipation',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
