# Generated by Django 6.0.6 on 2026-07-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_lessonparticipation_is_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonabsence',
            name='is_resolved',
        ),
    ]
