# Generated by Django 6.0.6 on 2026-07-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_lessonabsence_is_resolved'),
        ('users', '0002_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonabsence',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='lessonabsence',
            constraint=models.CheckConstraint(condition=models.Q(('makeup_lesson__isnull', True), models.Q(('makeup_start_time__isnull', True), ('makeup_end_time__isnull', True)), _connector='OR'), name='lesson_absence_not_both_makeup_lesson_and_custom_time'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exception_type', 'rescheduled'), _negated=True), ('new_date__isnull', False), _connector='OR'), name='schedule_exception_rescheduled_requires_new_date'),
        ),
        migrations.AddConstraint(
            model_name='scheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exception_type', 'cancelled'), _negated=True), models.Q(('new_date__isnull', True), ('new_start_time__isnull', True)), _connector='OR'), name='schedule_exception_cancelled_has_no_new_date_or_time'),
        ),
    ]
